### ISSUE TITLE
"02_vectors" -> which()

### ISSUE THREAD

**Issue by martialbriand** [dputhier/rtrainer#16]
Merci beaucoup pour ces tutos.
Pour la question :
"Stockez dans z toutes les positions pour lequelles les valeurs de x et de y sont les mêmes"
La réponse ne serait-elle pas z <- which (x==y) plutôt que z <- x == y ?
Idem question "Stockez dans z toutes les positions pour lesquelles les valeurs de x et y diffèrent."
Réponse z <- which(x != y) au lieu de z <- x != y ?
Cordialement,
martal

**Comment by dputhier** [comment]
Bonjour Martial,
Merci pour vos remerciements. 
Vous avez tout à fait raison. Il en est de même pour les 2 questions suivantes. 
J'ai réglé ça dans le commit c50533985f778fbfb43befa24bac57777317332b
Très cordialement
